macros = [
    {}
]

arguments = [
    { name = "enable", label = "Enable", description = "The event which enables the bluetooth gateway.", type = "string" },
    { name = "disable", label = "Disable", description = "The event which disables the bluetooth gateway.", type = "string" },
]

lines = [
    # Enable BLE gateway on enable if not in restricted mode.
    ["$enable", "power.is_restricted_mode.0", "ble.enable_gateway.0"],

    # Disable BLE gateway upon recieving disable event.
    ["$disable", "ble.is_gateway_enabled.0", "ble.disable_gateway.0"],
]
