macros = [
    {}
]

arguments = [
    { name = "enable", label = "Enable", description = "The event to enable diagnostic PGNs.", type = "string" }
]
 
lines = [
    # Enable diagnostics PGNs upon recieving enable event.
    ["$enable", "", "diagnostic.enable.0"],
]
