macros = [
    {}
]

arguments = [
    { name = "input", label = "Input", description = "Input (0-based) indicating the power status.", type = "integer" },
    { name = "on_signal", label = "ON Signal", description = "The value representing a ON equipment power status.", type = "boolean" },
    { name = "off_signal", label = "OFF Signal", description = "The value representing a OFF equipment power status.", type = "boolean" }
]

lines = [
    # Inform equipment of power CoS
    ["io.input_high.$input", "", "equipment.inform_power.$on_signal"],
    ["io.input_low.$input", "", "equipment.inform_power.$off_signal"],
]
