macros = [
  {},
]

arguments = [
    { name = "cos_index", label = "COS Index", description = "The index to the J1939 change of state fields.", type = "integer" },
    { name = "test_index", label = "Test Index", description = "The index to the J1939 test fields representing bitmasked J1939 data.", type = "integer" },
    { name = "set_stow_value", label = "Set Stow Value", description = "The stow value to compare against the test value.", type = "integer" },
    { name = "debounce_timeout", label = "Debounce Timeout", description = "The time (ms) to wait before sending a stow report message.", type = "integer", min = "1"},
    { name = "clear_stow_value", label = "Clear Stow Value", description = "The decimal value representing a binary bit mask.",type="integer" },
    { name = "input_index", label = "Input Index", description = "Input (0-based) indicating the stowed status.", type = "integer" },
]

lines = [
  # Use COS to trigger a value test of bitmasked j1939 data and set equipment stow status
  ["j1939.cos.$cos_index", "j1939.test_equals.$test_index.$set_stow_value", "timer.after.^stow_debounce.$debounce_timeout"], 
  
  # If unstow is detected check for active stow debounce and cancel
  ["j1939.cos.$cos_index", "j1939.test_equals.$test_index.$clear_stow_value and timer.active.^stow_debounce", "timer.cancel.^stow_debounce"], 
  
  # Check if stow goes high and set kv if yes
  ["timer.expired.^stow_debounce", "", "equipment.set_stowed_status.0"], 
  
  # Start timer to check stow and keyswitch
  ["j1939.cos.$cos_index", "j1939.test_equals.$test_index.$clear_stow_value", "timer.after.^unstow_debounce.$debounce_timeout"], 
  
  # If stow is detected check for active unstow debounce and cancel
  [
    "j1939.cos.$cos_index",
    "j1939.test_equals.$test_index.$set_stow_value and timer.active.^unstow_debounce",
    "timer.cancel.^unstow_debounce",
  ], 
  
  #  Check keyswitch to verify if stow signal was valid
  ["timer.expired.^unstow_debounce", "io.is_high.$input_index", "equipment.clear_stowed_status.0"],
]
