macros = [
  {},
]

lines = [
  # On wake up check KV for stow
  ["power.power_or_wake_up.0", "kv.exists.$stow_register", "equipment.set_stowed_status.0"],
  ["power.power_or_wake_up.0", "not kv.exists.$stow_register", "equipment.clear_stowed_status.0"], 
  
  # On stow or unstow event, save value to kv register 
  # this ensures that correct stow state is kept on warm/cold boot
  ["equipment.stowed.0", "", "kv.set.$stow_register.1"],
  ["equipment.unstowed.0", "", "kv.delete.$stow_register"],
]
