macros = [
    {}
]

arguments = [
    { name = "report_index", label = "Report Index", description = "Index to the report fields representing a GPS update message.", type = "integer"},
    { name = "signal", label = "Signal", description = "The value indicating a GPS fix deduced from a back a office message.", type = "integer"},
]

lines = [
    # Send in GPS report once per wake cycle upon acquiring a GPS Fix.
    ["gps.fix_acquired.0", "not report.last_sent_within.$report_index.0", "report.send_event.$report_index.$signal"],
]
