macros = [
    {}
]

arguments = [
    { name = "report_index", label = "Report Index", description = "Index to the report fields representing an ident message.", type = "integer" },
    { name = "duration", label = "Duration", description = "The time (ms) to wait to determine a valid device boot.", type = "integer", min = "1" }

]

lines = [
    # Send in an ident message on cold boots.
    ["power.power_up.0", "", "timer.after.^0.$duration"],
    ["timer.expired.^0", "", "report.send.$report_index"],
]
