macros = [
    {}
]
arguments = [
    { name = "report_index", label = "Report Index", description = "The report descriptor to send in on changes of state", type = "integer", min = "0", max = "4294967295" },
    { name = "duration", label = "Signal", description = "The time in milleseconds to wait before sending a report message upon a cold boot.", type = "integer", min = "0", max = "4294967295 "}

]
lines = [
    # Send in an ident message on cold boots.
    ["power.power_up.0", "", "timer.after.^0.$duration"],
    ["timer.expired.^0", "", "report.send.$report_index"],
]
