macros = [
    {}
]
arguments = [
       { name = "input", label = "Input", description = "The integer which denotes the 0 based harness pin number.", type = "boolean" }
]
lines = [
    ["io.input_high.$input", "", "keypad.stop_autocheckout.0"],
    ["io.input_low.$input", "", "keypad.start_autocheckout.0"],
]
