macros = [
    {}
]

arguments = [
       { name = "input", label = "Input", description = "Input (0-based) to drive auto checkouts.", type = "integer", min = 0 }
]

lines = [
    ["io.input_high.$input", "", "keypad.stop_autocheckout.0"],
    ["io.input_low.$input", "", "keypad.start_autocheckout.0"],
]
