macros = [
    {}
]

arguments = [
    { name = "delay_interval", label = "Delay Interval", description = "The time (ms) to wait before determining a valid device boot.", type = "integer", min = "1" },
    { name = "input", label = "Input", description = "Input (0-based) representing input change of state.", type = "integer" },
    { name = "report_index", label = "Report Index", description = "Index to the report fields representing an input change of state." }
]

lines = [
   # Start timer to allow device to boot up.
   ["power.power_or_wake_up.0", "", "timer.after.^bootup_delay.$delay_interval"],

   # Send out initial bootup CoS messages if input is HIGH.
   ["timer.expired.^bootup_delay", "io.is_high.$input and not report.last_sent_within.$report_index.1", "report.send_event.$report_index.$event_signal"],
   
   # CoS message on input going high.
   ["io.input_high.$input", "not timer.active.^bootup_delay", "report.send_event.$report_index.$event_signal"],

   # CoS message on input going low.
   ["io.input_low.$input", "not timer.active.^bootup_delay", "report.send_event.$report_index.$event_signal"],
 ]
 