macros = [
    {}
]

arguments = [
    { name = "off_condition", label = "OFF Condition", description = "Filter ensuring that the ECU is off.", type = "string" },
    { name = "report_index", label = "Report Index", description = "The index to the report fields representing a low threshold.", type = "integer" },
    { name = "index", label = "Index", description = "Threshold to reset if it's above threshold value.", type = "integer" }
]

lines = [
    # Send low threshold on disconnect.
    ["j1939.disconnected.0", "j1939.is_above_or_equal_threshold.$index and $off_condition", "report.send_event.$report_index.0"],
]
