macros = [
    {}
]
arguments = [
    { name = "index", label = "Index", description = "The boolean used to determine to send a low threshold on disconnect.", type = "boolean" },
    { name = "frequency", label = "Frequency", description = "The time in milliseconds to wait in order to check CAN connection status.", type = "integer", min = "0", max = "4294967295" },
    { name = "keyswitch_index", label = "Keyswitch Index", description = "The integer which represents where the keyswitch is located.", type = "integer", min = "0", max = "9223372036854775808" }
] 
lines = [
    # Complete on receiving.
    ["action.start.$index", "j1939.is_connected.0 and io.is_high.$keyswitch_index", "action.complete.$index"],

    # Begin delay until CAN connection and keyswitch high.
    ["action.start.$index", "not j1939.is_connected.0 or io.is_low.$keyswitch_index", "timer.every.^timeout.$frequency"],
    ["timer.expired.^timeout", "not j1939.is_connected.0 or io.is_low.$keyswitch_index", "action.heartbeat.$index"],

    # Complete action on a keyswitch transition.
    ["io.input_high.$keyswitch_index", "action.is_running.$index and j1939.is_connected.0", "action.complete.$index"],
    ["io.input_high.$keyswitch_index", "timer.active.^timeout and j1939.is_connected.0", "timer.cancel.^timeout"],

    # Complete action on a CAN connection.
    ["j1939.connected.0", "action.is_running.$index and io.is_high.$keyswitch_index", "action.complete.$index"],
    ["j1939.connected.0", "timer.active.^timeout and io.is_high.$keyswitch_index", "timer.cancel.^timeout"],
]
