macros = [
    {}
]

arguments = [
    { name = "index", label = "Index", description = "Index to the J1939 threshold repeated field that crossed.", type = "integer" },
    { name = "report_index", label = "Report Index", description = "Index to the report fields representing a threshold crossing.", type = "integer" },
]

lines = [
    # Send J1939 threshold messages.
    ["j1939.below_threshold.$index", "", "report.send_event.$report_index.0"],
    ["j1939.above_or_equal_threshold.$index", "", "report.send_event.$report_index.1"],
]
