macros = [
    {}
]

arguments = [
    { name = "delay_interval", label = "Delay Interval", description = "The time (ms) to wait before determining a valid CAN connection.", type = "integer", min = "1" },
    { name = "index", label = "Index (Read)", description = "The index to the J1939 memory access repeated field which indicates which memory access read to perform,", type = "integer" },
]

lines = [
    # Perform Read based on connection.
    ["j1939.connected.0", "", "timer.after.^delay.$delay_interval"], 
    ["timer.expired.^delay", "", "j1939.memory_read.$index"],
]
