macros = [
    {}
]

arguments = [
    { name = "start", label = "Start", description = "Event which starts timer accumulation incrementing by one second.", type = "string" },
    { name = "stop", label = "Stop", description = "Event which stops timer accumulation.", type = "string" },
    { name = "acc_index", label = "Accumulator Index ", description ="The key value representing the accumulated time.", type = "integer" }
]

lines = [
    # Enable accumulator time increments.
    ["$start", "", "kv.start_accumulating_time.$acc_index"],

    # Disbale accumulator time increments.
    ["$stop", "", "kv.stop_accumulating_time.$acc_index"],
]
