macros = [
	{},
]

arguments = [
    { name = "momentary_on", label = "Momentary ON", description = "The action to be executed denoted by the back office resulting in a high output.", type = "integer" },
    { name = "frequency", label = "Frequency", description = "Duration (ms) to keep the output high.", type = "integer", min = "1" },
    { name = "output", label = "Output", description = "Physical Output (0-based) to drive.", type = "integer" }
]

lines = [
	["action.start.$momentary_on", "", "timer.after.^momentary.$frequency"],
	["action.start.$momentary_on", "io.is_low.$output", "io.set_high.$output"],
	["action.start.$momentary_on", "", "action.complete.$momentary_on"],
	["timer.expired.^momentary", "io.is_high.$output", "io.set_low.$output"],
]
