macros = [
	{},
]
arguments = [
    { name = "momentary_on", label = "Momentary ON", description = "The integer which turns the io output HIGH.", type = "integer", min = "0", max = "4294967295" },
    { name = "frequency", label = "Frequency", description = "The integer which determines which io pin to output.", type = "integer", min = "0", max = "4294967295" },
    { name = "output", label = "Output", description = "The integer which turns the io output HIGH.", type = "integer", min = "0", max ="9223372036854775808" }
]
lines = [
	["action.start.$momentary_on", "", "timer.after.^momentary.$frequency"],
	["action.start.$momentary_on", "io.is_low.$output", "io.set_high.$output"],
	["action.start.$momentary_on", "", "action.complete.$momentary_on"],
	["timer.expired.^momentary", "io.is_high.$output", "io.set_low.$output"],
]
