macros = [
    {}
]

arguments = [
    { name = "frequency", label = "Frequency", description = "Duration (ms) before determining restricted mode status.", type = "integer", min = "1" },
    { name = "unrestricted_value", label = "Unrestricted Value", description = "Key value representing a unrestricted mode status.", type = "boolean" },
    { name = "restricted_value", label = "Restricted Value", description = "Key value representing a restricted mode status.", type = "boolean" },
    { name = "rm_register", label = "Restricted Mode Register", description = "Register storing the restricted mode.", type = "integer" },
]

lines = [
    # Arm recurring timer for checking Restricted Mode status.
    ["power.power_or_wake_up.0", "", "timer.every.^rm_update.$frequency"],

    # Set Restricted Mode register values when timer expires.
    ["timer.expired.^rm_update", "power.is_restricted_mode.0", "kv.set.$rm_register.$unrestricted_value"],
    ["timer.expired.^rm_update", "power.is_restricted_mode.1 or power.is_restricted_mode.2", "kv.set.$rm_register.$restricted_value"],

    # TODO: Send in register CoS message.
]
