macros = [
    {}
]

arguments = [
    { name = "frequency", label = "Frequency", description = "The Rate (ms) of sending a site survey message.", type = "integer", min = "1" },
    { name = "enable", label = "Enable", description = "Event which enables the site survey functionality.", type = "string" },
    { name = "disable", label = "Disable", description = "Event which disables the site survey functionality.", type = "string" },
]

lines = [
    # Send in site survey message when timer expires.
    ["$enable", "power.is_restricted_mode.0", "timer.every.^survey.$frequency"],
    ["timer.expired.^survey", "power.is_restricted_mode.0", "ble.site_survey.0"],

    # Disable timer upon recieving disable event.
    ["$disable", "timer.active.^survey", "timer.cancel.^survey"],
]
