macros = [
    {}
]

arguments = [
	{ name = "Z_low", label = "12V Low", description = "12V min value.", datatype = "integer", min = "0", max = "200" },
	{ name = "A_low", label = "12V Low", description = "12V min value.", datatype = "integer", min = "100", max = "300" },
    { name = "A_high", label = "12V High", description = "12V max value.", datatype = "integer", min = "100", max = "10000" },
    { name = "B_low", label = "24V Low", description = "24V min value.", datatype = "boolean" },
    { name = "B_high", label = "24V High", description = "24V max value.", datatype = "string" },
	{ name = "report_index", label = "24V Low", description = "24V min value.", datatype = "integer" },
	{ name = "below_signal", label = "24V Low", description = "24V min value.", datatype = "integer" },
    { name = "above_signal", label = "24V High", description = "24V max value.", datatype = "integer" },
	{ name = "debounce_interval", label = "Debounce Interval", description = "debounce interval.", datatype = "integer"},
	{ name = "system_median", label = "System Median", description = "system median.", datatype = "integer"}
]

lines = [
    # Send on crossing analog thresholds on 12V systems.
    ["adc.below_threshold.$A_low", "not timer.active.^above_timer", "timer.after.^below_timer.$debounce_interval"],
    ["adc.below_threshold.$A_low", "timer.active.^above_timer", "timer.cancel.^above_timer"],

    ["adc.above_threshold.$A_high", "not timer.active.^below_timer and adc.is_below_threshold.$system_median", "timer.after.^above_timer.$debounce_interval"],
    ["adc.above_threshold.$A_high", "timer.active.^below_timer and adc.is_below_threshold.$system_median", "timer.cancel.^below_timer"],

    # Send on crossing analog thresholds on 24V systems.
    ["adc.below_threshold.$B_low", "adc.is_above_threshold.$system_median", "timer.after.^below_timer.$debounce_interval"],
    ["adc.below_threshold.$B_low", "adc.is_above_threshold.$system_median and timer.active.^above_timer", "timer.cancel.^above_timer"],

    ["adc.above_threshold.$B_high", "not timer.active.^below_timer", "timer.after.^above_timer.$debounce_interval"],
    ["adc.above_threshold.$B_high", "timer.active.^below_timer", "timer.cancel.^below_timer"],

    # Send register threshold reports after debounce interval.
    ["timer.expired.^below_timer", "", "report.send_event.$report_index.$below_signal"],
    ["timer.expired.^above_timer", "", "report.send_event.$report_index.$above_signal"],
]
