macros = [
    {}
]
lines = [
   # Start timer to allow device to boot up.
   ["power.power_or_wake_up.0", "", "timer.after.^bootup_delay.$delay_interval"],

   # Send out initial bootup CoS messages if input is HIGH.
   ["timer.expired.^bootup_delay", "io.is_high.$input and not report.last_sent_within.$report_index.1", "report.send_event.$report_index.$event_signal"],
   
   # CoS message on input going high.
   ["io.input_high.$input", "not timer.active.^bootup_delay", "report.send_event.$report_index.$event_signal"],

   # CoS message on input going low.
   ["io.input_low.$input", "not timer.active.^bootup_delay", "report.send_event.$report_index.$event_signal"],
 ]
