macros = [
    {}
]

lines = [
    # Catch the change of state for Tak.
    ["j1939.cos.$cos_index", "", "j1939.tak_value_updated.$cos_index"], 

    # Report when we have memory read data.
    ["j1939.memory_read_complete.0", "", "report.send_event.$report_index.$event_signal"], 
]
