macros = [
    {}
]

lines = [
    # Enable accumulator time increments.
    ["$start", "", "kv.start_accumulating_time.$acc_index"],

    # Disbale accumulator time increments.
    ["$stop", "", "kv.stop_accumulating_time.$acc_index"],
]
