arguments = [
	{ name = "active_profile", label = "Active profile", description = "test descp", datatype = "boolean" },
    { name = "sleep_profile", label = "Sleep profile", description = "test descp", datatype = "boolean" }
]
