[[module]]
name = "power"
uuid = "abbbd3832ad747a0a1b0cd1b3c6d6579"
[module.config]
profiles = [
    { state = 0 },
    { state = 1, wakeup_mask = 39, delay_s = 300 },
    { state = 2, wakeup_mask = 3, delay_s = 120 },
]
test = 200

[[module]]
name = "io"
uuid = "2fa4f8500e044f92b1368164d8e1e49c"
[module.config]
analog_inputs = [{ adc_input = 0, digital_input = 4, set_value = 5000, clear_value = 2000 }]
input_debounce_interval = [10, 20, 30]

[network]
blocks = [
    { type = "sleep-behaviour", args = { active_profile = "0", sleep_profile = "1" } },
    { type = "ident-messages", args = { duration = "45000", report_index = "1" } },
]