[[module]]
name = "power"
uuid = "abbbd3832ad747a0a1b0cd1b3c6d6579"
[module.config]
profiles = [
  {state = 0},
  {state = 1, wakeup_mask = 39, delay_s = 300}, # 5 min timer before sleep.
  {state = 2, wakeup_mask = 3, delay_s = 120}, # 2 min timer before hibernate.
]
test123 = 10

[[module]]
name = "timer"
uuid = "018e7e898ac74a06936fab03b5fc6094"

[[module]]
name = "adc"
uuid = "2e48782d9d424b678c583755877fa687"
[module.config]
thresholds = [
  {index = 2, value = 11100}, # 11.1V
  {index = 2, value = 12000}, # 12.0V
  {index = 2, value = 18000}, # 18.0V
  {index = 2, value = 22200}, # 22.2V
  {index = 2, value = 24000}, # 24.0V
]

[[module]]
name = "io"
uuid = "2fa4f8500e044f92b1368164d8e1e49c"
[module.config]

[[module]]
name = "kv"
uuid = "1d376724b74c40bc86aa4ee57441b9dd"
[module.config]
defaults = [
  {key = 1, value = 0}, # Used for restricted mode status.
  {key = 4, value = 0}, # Used for accumulator 0 key.
  {key = 5, value = 0}, # Used for accumulator 1 key.
]
sync_frequency_minutes = 15
test_var=30

[[module]]
name = "report"
uuid = "69fdf7ae3d5011eab77f2e728ce88125"
[module.config]
inbound_port = 5683
inbound_server = "m7-gw.staging.telematics.equipment"
maintenance_checkin_interval = 1440
maintenance_inbound_port = 5683
maintenance_server = "m7.m.staging.telematics.equipment"
reports = [
  # Periodic message.
  {uri_index = 1, block_bitmask = 279, block_config = []}, 
  
  # Ident message.
  {uri_index = 2, block_bitmask = 0, block_config = []}, 
  
  # IO CoS.
  {uri_index = 0, block_bitmask = 51, block_config = [
    {index = 5, arg = 1},
  ]},
  {uri_index = 0, block_bitmask = 50, block_config = [
    {index = 5, arg = 10},
  ]}, 
  
    # J1939 Comm Status.
  {uri_index = 0, block_bitmask = 53, block_config = [
    {index = 5, arg = 20},
  ]}, 
  
    # J1939 CoS.
  {uri_index = 0, block_bitmask = 36, block_config = [
    {index = 5, arg = 21},
    {index = 2, arg = 65281},
  ]},
  {uri_index = 0, block_bitmask = 36, block_config = [
    {index = 5, arg = 21},
    {index = 2, arg = 20481},
  ]},
  {uri_index = 0, block_bitmask = 36, block_config = [
    {index = 5, arg = 21},
    {index = 2, arg = 20492},
  ]}, 
  
  # J1939 Threshold.
  {uri_index = 0, block_bitmask = 52, block_config = [
    {index = 5, arg = 22},
    {index = 2, arg = 65253},
  ]},
  {uri_index = 0, block_bitmask = 52, block_config = [
    {index = 5, arg = 22},
    {index = 2, arg = 61444},
  ]},
  
      # J1939 Fault Resync.
  {uri_index = 0, block_bitmask = 40, block_config = [
    {index = 5, arg = 24},
  ]}, 
  
      # J1939 Faults.
  {uri_index = 0, block_bitmask = 60, block_config = [
    {index = 5, arg = 23},
  ]}, 
  
      # Register Threshold.
  {uri_index = 0, block_bitmask = 50, block_config = [
    {index = 5, arg = 11},
  ]}, 
  
      # GPS Fix Report.
  {uri_index = 0, block_bitmask = 48, block_config = [
    {index = 5, arg = 5},
  ]},
  
  	# Memory Read.
  {uri_index = 0, block_bitmask = 36, block_config = [
    {index = 5, arg = 25},
  ]},
]

[[module]]
name = "register"
uuid = "e757221195064b5ba9a93be57b2967b1"
[module.config]
analog_registers = [
  {index = 2, arg = 1}, # Internal battery mv.
  {index = 3, arg = 2}, # External battery mV.
  {index = 6, arg = 0}, # Analog raw mV.
]
digital_registers = [
  {config = {index = 0, arg = 4}, bit = 1}, # Analog threshold.
]
kv_registers = [
  {index = 1, arg = 1}, # Restricted mode status.
  {index = 4, arg = 4}, # Input 0 accumulator.
  {index = 5, arg = 5}, # Input 1 accumulator.
]

[[module]]
name = "j1939"
uuid = "ac0e4b9c567a4f629b6f472d9ca138ce"
[module.config]
pdu = 1
change_of_state = [
  {datapoint = {offset = 0, length = 8, id = 65281}, bitmask = [0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF]},
  {datapoint = {offset = 4, length = 1, id = 20481}, bitmask = [0x01]},
  {datapoint = {offset = 0, length = 1, id = 20492}, bitmask = [0x3F]},
  {datapoint = {offset = 0, length = 4, id = 20659}, bitmask = [0xFF, 0xFF, 0xFF, 0x00]},
]
memory_access = {kex = 1, cipher = 1, read_requests = [
  {address = 228, pointer_type = 0, pointer = 1, pointer_extension = 0, length = 96},
  {address = 206, pointer_type = 0, pointer = 1, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 1, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 5, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 9, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 13, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 17, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 21, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 25, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 29, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 33, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 37, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 41, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 45, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 49, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 53, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 57, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 61, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 65, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 69, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 73, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 77, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 81, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 85, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 89, pointer_extension = 0, length = 4},
  {address = 228, pointer_type = 0, pointer = 93, pointer_extension = 0, length = 4},
]}
raw = [
  {id =	20481, address = 255},
  {id = 20482, address = 255},
  {id =	20483, address = 255},
  {id =	20488, address = 255},
  {id =	20490, address = 255},
  {id =	20492, address = 255},
  {id =	20493, address = 255},
  {id = 20497, address = 255},
  {id =	20549, address = 255},
  {id =	20550, address = 255},
  {id =	20551, address = 255},
  {id =	20552, address = 255},
  {id =	20553, address = 255},
  {id = 20659, address = 255},
  {id =	61443, address = 255},
  {id =	61444, address = 255},
  {id =	62465, address = 255},
  {id =	64800, address = 255},
  {id =	64891, address = 255},
  {id =	64892, address = 255},
  {id =	64946, address = 255},
  {id =	64947, address = 255},
  {id =	64948, address = 255},
  {id =	65110, address = 255},
  {id =	65241, address = 255},
  {id =	65242, address = 255},
  {id =	65243, address = 255},
  {id =	65257, address = 255},
  {id =	65262, address = 255},
  {id =	65263, address = 255},
  {id =	65266, address = 255},
  {id =	65269, address = 255},
  {id =	65270, address = 255},
  {id =	65271, address = 255},
  {id =	65276, address = 255},
  {id =	65281, address = 255},
  {id =	65283, address = 255},
  {id = 65293, address = 255},
  {id =	65297, address = 255},
  {id =	65299, address = 255},
  {id =	65322, address = 255},
  {id =	65361, address = 255},
]
request = [
  {id = 65242},
]
thresholds = [
  {datapoint = {offset = 0, length = 1, id = 65253}, value = 0},
  {datapoint = {offset = 3, length = 2, id = 61444}, value = 4000},
]

[[module]]
name = "ble"
uuid = "20e7068614e94d4980cbffce06f71433"
[module.config]
connect_message_threshold = 8
disconnect_message_threshold = 4
max_scan_results = 30
scan_message_threshold = 0
sort_by = 4

[[module]]
name = "diagnostic"
uuid = "4947e836d9414a2ab59e260b52e5e252"

[[module]]
name = "cron"
uuid = "c609d032bc7844aba78ef3044d9fbec5"

[[module]]
name = "gps"
uuid = "edce8ad7992042ecb031bff36e195163"

[network]
blocks = [
    { type = "sleep-behaviour", args = { active_profile = "0", sleep_profile = "1" } },
    { type = "ident-messages", args = { duration = "45000", report_index = "1" } },
]
